app:
  image:
    tag: latest
  replicas: 1

resources:
  app:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "768Mi"
      cpu: "250m"
  postgres:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "512Mi"
      cpu: "250m"

ingress:
  enabled: true
  host: spring-petclinic-staging.localhost

storage:
  size: 512Mi


